name: Check for updates

on:
    schedule:
      - cron: "0 0 1 * *" # every 1st of the month at 00:00 UTC

jobs:
    checkForUpdates:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Check for outdated dependencies
          run: |
                cargo install cargo-outdated
                cargo outdated --exit-code 1
